CREATE USER IF NOT EXISTS SA SALT '13915e1c84835119' HASH '8e9ed45dbcae3693c703712255d14c6d9c7ba909b92f648336831fc445878dad' ADMIN;
CREATE SCHEMA IF NOT EXISTS THECLASH AUTHORIZATION SA;
CREATE CACHED TABLE THECLASH.JEUGDHUIZEN( 
    ID INTEGER NOT NULL, 
    NAME CHAR(25), 
    AANTALDRANKEN INTEGER, 
    EIGENAAR INTEGER 
);
ALTER TABLE THECLASH.JEUGDHUIZEN ADD CONSTRAINT THECLASH.CONSTRAINT_7 PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM THECLASH.JEUGDHUIZEN;
CREATE CACHED TABLE THECLASH.ACCOUNTS( 
    ID INTEGER NOT NULL, 
    NAME CHAR(25) 
);
ALTER TABLE THECLASH.ACCOUNTS ADD CONSTRAINT THECLASH.CONSTRAINT_A PRIMARY KEY(ID);
-- 0 +/- SELECT COUNT(*) FROM THECLASH.ACCOUNTS;